apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xlx4nribl-go 
  janus-idp.io/tekton: xlx4nribl-go
  backstage.io/kubernetes-id: xlx4nribl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xlx4nribl-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml