apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xlx4nribl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xlx4nribl-go 
  name: xlx4nribl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xlx4nribl-go 
